### ISSUE TITLE
Ellie inserts text after a Gmail signature 

### ISSUE THREAD

**Issue by Jivings** [squarecat/ellie#1]
With these settings the reply text is inserted in the wrong place:

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/1462828/208134848-6ab2e9c6-d0ec-43ea-94cb-758ba49bbef0.png">

**Comment by pgl252** [comment]
Same exact issue for me

**Comment by Jivings** [comment]
✅ This is fixed in the next version - just waiting on review on the extension stores

**Comment by dinkydani** [comment]
Fixed in release 0.2.0 🚀
