### ISSUE TITLE
German email generation fails massively

### ISSUE THREAD

**Issue by marcelreschke** [squarecat/ellie#13]
Hi,

As English email generation is ok. Works for answers I write out of politeness and for acknowledgment. But German email generation is a total mess. It copies parts of the original mail. Sometimes word-by-word copies, sometimes it rewrites the original mail. In some cases, it seems as if the courser is jumping while writing, which ends in total gibberish. 

Hope Ellie will improve, but as for now I won't upgrade.

**Comment by Jivings** [comment]
Hey @marcelreschke! Thanks for letting me know 👍

I've published a huge update yesterday that should help with this hopefully. Can you let me know if you see any improvement? 🙏

**Comment by Jivings** [comment]
I've had no more language reports so closing this
