### ISSUE TITLE
Romanian language errors lack of logic

### ISSUE THREAD

**Issue by pauldumbravanu1** [squarecat/ellie#15]
![image](https://user-images.githubusercontent.com/124055273/216790494-d73dca1e-a097-493a-98c1-e3ed69a7e8b1.png)
![image](https://user-images.githubusercontent.com/124055273/216790568-eece8464-7243-4d12-9186-cdbd2b4310e2.png)

many errors - writing grammar and others. tried other tools and worked better -superReply

**Comment by Jivings** [comment]
Hey, we just shipped a huge improvement yesterday that should improve non-English language replies. Would love if you could give it another try and let me know 🙏

**Comment by Jivings** [comment]
I've had no more language reports so closing this
