### ISSUE TITLE
Giberrish reply to Greek email

### ISSUE THREAD

**Issue by anna-filou** [squarecat/ellie#16]
<img width="697" alt="Screen Shot 2023-02-28 at 17 50 34" src="https://user-images.githubusercontent.com/38259055/221906018-58da0adb-bdca-4f0f-9bac-b7be3e863f1e.png">

It starts writing in Greek alright (but does NOT use respectful language as I specified, which the sender also uses), then switches to unintelligible gibberish, then Greek but written with Latin characters. Obviously unusable.

**Comment by Jivings** [comment]
Unfortunately the OpenAI API is not very good at Greek.

That said we shipped a big update yesterday that should improve it bit if you wanted to give it another go 🙏
