### ISSUE TITLE
Ellie stops working in email clients after the extension updates

### ISSUE THREAD

**Issue by saschaurban** [squarecat/ellie#17]
When clicking on the "Write" button in the gmail interface, it's processing ("Thinking") but then doesn't paste any text into the e-Mail field.

(Language English).

**Comment by Jivings** [comment]
Hey @saschaurban, do you have any other Gmail extensions installed? It could be that Ellie is conflicting with one of them.

Also after an upgrade or initial install of Ellie sometimes you need to refresh the Gmail tab in order for Ellie to insert text again, I'm not sure why this happens.

**Comment by saschaurban** [comment]
No other Google Chrome extension other than 1Password.
It's been working today. I'll observe it a few days and follow up on this if it happens again.

**Comment by Jivings** [comment]
I think probably the refresh issue then, I'll see if I can get that sorted with the next release 🙏

**Comment by saschaurban** [comment]
I don't have this issue anymore so from my perspective we can close this.

**Comment by Jivings** [comment]
I'm going to release a new update in the next few days, so lets see if it happens again! If not then I'll close :)

**Comment by dinkydani** [comment]
Closing as the issue didn't happen again! :)
