### ISSUE TITLE
Incorrect interest in new version

### ISSUE THREAD

**Issue by dreameruk** [squarecat/ellie#19]
The new version seems to be getting 'Not Interested' wrong quite a few times, for example:

[
![Screenshot 2023-03-23 101355](https://user-images.githubusercontent.com/14836612/227172305-328306b6-bf67-4ddd-b3a3-ac49adfdd193.png)
](url)

**Comment by Jivings** [comment]
Hm, yes it seems the new AI model has more of an emphasis on "being nice". I'll see what I can do to fix it in the next version!

**Comment by Jivings** [comment]
I think this is working better now, what do you think @dreameruk?
