### ISSUE TITLE
Ellie mixing up languages

### ISSUE THREAD

**Issue by saschaurban** [squarecat/ellie#20]
I'm writing mails in German and English. It seems as if Ellie can't pick the right language.

Example:

(This text was composed by Ellie in German)
Hallo Mark,
Danke für deine Nachfrage bezüglich Ralf und deinem Engagement. Es tut mir leid, dass ich nicht auf deine vorherige E-Mail geantwortet habe. Obwohl Ralfs Fähigkeiten und Erfahrungen beeindruckend sind, haben wir derzeit bei Blinks Labs GmbH (Blinkist) keine passenden Projekte für seine spezielle Nische.
Wir schätzen dein Interesse und das Angebot, uns sicherkönseinegebenZukunfttenRalfs lichProfil zukommen zu lassen. Soll sich in der Projekte er, bei denen wir Fähigkeiten anbenötigennten, werden wir uns dich wenden.
Vielen Dank und beste Grüße,
Sascha

(but this was the e-Mail I wanted to reply to, which is obviously in English)
On Fri, 24 Mar 2023 at 09:29, Mark Tipping <mark.tipping@venturi-group.com> wrote:
Hi Sascha, 
 
With you not responding to my previous email regarding Ralf, I presume Ralf’s skills was completely off the base to what you use at your company.
 
Would I be right in thinking Ralf is irrelevant for any projects or did you just miss the email? 
 
If it is the latter, would you be interested in seeing the profile for any ongoing or upcoming projects? You won't be disappointed in the niche skillset. 
 
Many thanks,

**Comment by Jivings** [comment]
I've had a few people raise this same issue with Ellie choosing the wrong language and I can't figure out why it would do this. It should only be able to use the recent reply to choose a language. 

Can you tell me if your Gmail is set to German? Maybe Ellie is reading some markup from the page that is in German.

Also have you provided Ellie with example emails in the settings? Are they in English or German?

Thanks for your help!

**Comment by Jivings** [comment]
I tweeted about this problem and it appears to be happening to other people too (without explanation).

https://twitter.com/marckohlbrugge/status/1640238386610044930?s=20

**Comment by saschaurban** [comment]
My gmail is actually in English as well (company language).
But I do regularly receive German e-Mails or reply in German, so both languages are in my inbox.

**Comment by Jivings** [comment]
Ellie should only use the information in the email it's replying to, so it shouldn't matter that you have other German emails. Somehow it's being too smart and I need to figure out why!

**Comment by saschaurban** [comment]
Just happened today again. It wrote a German answer to an English mail ^^It definitely seems to use more than just the mail at hand. Does Ellie use past e-Mails I used?  Because I read somewhere that it's "learning" from my past answers, so I assume it's storing this data to train?

**Comment by Jivings** [comment]
Currently it should only be using the emails in the training examples that you provide in the settings. If you haven't provided any then it is *only* using the email thread, no past emails.

**Comment by Jivings** [comment]
I've made some changes to the prompt today that might improve this situation 🤞 please let me know if it happens again
