### ISSUE TITLE
My first reply was blocked

### ISSUE THREAD

**Issue by rodrigosramos** [squarecat/ellie#21]
I´ve just created an account and tried to reply to the email I received from Ellie to test the service, but I couldn't because, despite it being my first use, it seems that I don't have any reply left to use. By the way, I received two emails with key licenses, and I also installed the chrome extension.
![image](https://user-images.githubusercontent.com/130875669/232259210-14e14172-6691-49d0-9e10-949728c09d64.png)

**Comment by Jivings** [comment]
Hey! Thanks for trying Ellie :)

You need to enter a licence key to use Ellie for free, this is so we can track how many replies everyone is making. You can get one on the downloads page: https://tryellie.com/downloads/

**Comment by Jivings** [comment]
Hey! Thanks for trying Ellie :)

This is saying you haven't entered the licence key, if you click the ? button at the top right of that screenshot it will take you to the settings page where you can enter the key.
