### ISSUE TITLE
Ellie is being exteremly slow to type and sometimes it doesn't type - need help fixing this

### ISSUE THREAD

**Issue by salfierro** [squarecat/ellie#23]

**Comment by Jivings** [comment]
Hey, I updated Ellie to use GPT-4 which is much smarter, but a bit slower. 

In the newest Ellie version (1.4.0) if you want to use the faster AI model (GPT-3.5-Turbo), then you can switch it back to use that on the settings page. Hopefully a bit better for you. Just waiting for it to go live on the extension stores, should be updated today.

**Comment by zachthehoff** [comment]
I've had this issue several times today. Would love some help -- Ellie's a great tool, but I won't keep using it if it doesn't produce.

-thanks

**Comment by Jivings** [comment]
Is it better today? [OpenAI had loads of errors yesterday](https://status.openai.com/) - we retry failed requests but it causes it to take longer.

Unfortunately if the problem is with OpenAI then there's nothing we can do about it

**Comment by Jivings** [comment]
It looks like we're still getting this response from OpenAI a lot:

```
OpenAI request failed: 429 Too Many Requests
Response: {
 "message": "That model is currently overloaded with other requests. You can retry your request, or contact us through our help center at help.openai.com if the error persists. (Please include the request ID 7c1da22442694f471a1754982590eef5 in your message.)",
  "type": "server_error",
  "param": null,
  "code": null
}
```

Retrying works, which is what we currently do.
This is using 3.5-turbo, it's possible we could fall back to GPT3 if we see this message, but it probably wont improve the speed at all.
