### ISSUE TITLE
Problem after upgrade

### ISSUE THREAD

**Issue by jesper-adeberg** [squarecat/ellie#24]
After I've upgraded to a paid plan, unfortunately, the extension (using gmail) stopped working. It sort of works, but it throws around text, sentences and connect words that should be connected. For example, one sentence lands under my signature and it seems as if the words have been shuffled.

How can we solve this?

**Comment by salfierro** [comment]
Yeah, it used to be 10x better, and the API is a lot slower now.

**Comment by Jivings** [comment]
Hey, that's strange. Can you drop me a screenshot? 

Regarding the speed, most requests for paid users are using GPT-4 now, which is slightly slower (but more intelligent). In the latest update ([1.4.0](https://github.com/squarecat/ellie/releases/tag/1.4.0)) I've added an option so you can change it back to GPT-3.5-Turbo if you want, which is the much faster model.

**Comment by jesper-adeberg** [comment]
Thanks James,

I'll send a screenshot if it happens again (magically solved itself after
10-15 tries.. weird.

Thanks for letting me know regarding GPT4 vs 3,5

Best, Jesper

Den tis 2 maj 2023 kl 11:08 skrev James Ivings ***@***.***>:

**Comment by Jivings** [comment]
It could be related to [this bug](https://github.com/squarecat/ellie/issues/7), if it happens again try disabling the spellchecker!

**Comment by jesper-adeberg** [comment]
Hi James, nice to hear from you!

Hmm, does not seem so. 

Attached is an example when the reply was supposed to be in Swedish. But as you can see, things are thrown around and nothing makes sense.
Perhaps this helps you?

Im using the Chat GPT 4 selection.

Best, Jesper

￼

**Comment by Jivings** [comment]
@jesper-adeberg you replied via email so I haven't received the attachment, can you come attach it to the Github ticket?

**Comment by jesper-adeberg** [comment]
![Screenshot 2023-05-03 at 15 49 02](https://user-images.githubusercontent.com/132050000/236795318-552c4105-13fc-45d3-8984-c907f75f7dfd.png)

Here it is!

**Comment by Jivings** [comment]
@jesper-adeberg is this happening a lot? I can't think of any reason for it except if the cursor is jumping around, like happens with the spell checker. Can you try turning off spelling & grammar checking in the Gmail settings and seeing if it still happens?
