### ISSUE TITLE
Ellie sometimes replies in the wrong language

### ISSUE THREAD

**Issue by Jivings** [squarecat/ellie#25]
We think that Ellie chooses the language somewhat at random if there are multiple languages in the email, causing it to reply sometimes in a language that is only present in the email signature and not in the email content.

We should be able to fix this with a prompt chain, will investigate this week 👍

**Comment by james-william-r** [comment]
We've made some improvements to translation detection which hopefully means this is no longer an issue, but are keeping an eye on it for the time being. Let us know if you're still encountering issues with incorrect response languages. 🙏
