### ISSUE TITLE
Mail is complete gibberish.

### ISSUE THREAD

**Issue by thursd4y** [squarecat/ellie#27]
It does not write coherent text but starts to jumps around and writes in random locations, making it useless. 

Example:
zuCheitGebereitsogensdesZusheentschuldigen Sie die späte Antwort, ich war im Urlaub. Vielen Dank für Ihre Mü und .     SeiteInformationenuelligeundlegendieIchdieendung   von,   ichdiemithatteFrageb  aktIhremTO sprechen nötigen Informationen zu erhalten. Daher benöt keine weiteren Ihrer.

**Comment by Jivings** [comment]
Hey, there's a bug with the spelling + grammar checker in Gmail that causes the cursor to jump around. 

Can you try disabling the spelling + grammar check in Gmail and then Ellie should work fine. I've been working on a fix but it's not easy to know what the correct solution is.
