### ISSUE TITLE
Reading disclaimer

### ISSUE THREAD

**Issue by dreameruk** [squarecat/ellie#4]
It reads the email disclaimer, in the email sent to you, and adds it to the reply.

The email had this disclaimer:

```
"Disclaimer

The information contained in this email may be confidential. It has been sent for the sole use of the intended recipient(s). If the reader of this email is not an intended recipient, you are hereby notified that any unauthorized review, use, disclosure, dissemination, distribution, or copying of this message is strictly prohibited. If you have received this email in error, please notify the sender immediately and destroy all copies of the message.

For more information on how we process personal data please see XXXXXX. Please note that neither the Company nor the sender accepts any responsibility for viruses and it is your responsibility to scan or otherwise check this email and any attachments.

```

So it added this to the reply:

"Please note that neither the Company nor myself accept any responsibility for viruses, so it is my responsibility to scan all emails and attachments for viruses before opening them."

Be good if there was a setting to disable it reading email disclaimers in settings.

**Comment by Jivings** [comment]
Hm.. interesting. I'm not sure how to do this but I'll think about it

**Comment by Jivings** [comment]
Hey @dreameruk, can you try this again and see how it performs? Ellie had a major update last week and I think it should now behave better with things like this

**Comment by dreameruk** [comment]
Sorry for delay in replying, yep this does not seem to be an issue any more. Thank you!

**Comment by Jivings** [comment]
No problem!
