### ISSUE TITLE
The Gmail autocorrect + grammar check conflicts with Ellie's writing

### ISSUE THREAD

**Issue by Jivings** [squarecat/ellie#7]
When Gmail grammar or spelling check functionality creates underlines in the text, it inserts stuff into the textarea. 

If Ellie is typing when this happens then Ellie loses track of it's position and starts inserting text in the wrong place.

**Comment by Jivings** [comment]
I think with the latest version of Ellie we're writing the output so fast that this is no longer a problem. But I'll leave this open for now just in case.

**Comment by Jivings** [comment]
This still happens sometimes, reopening

**Comment by james-william-r** [comment]
Just dropping this link in case anyone's wondering how to disable spelling and grammar auto-correction in Gmail: https://support.google.com/mail/answer/7987?hl=en

**Comment by james-william-r** [comment]
Fixed in [v2.3.1](https://github.com/squarecat/ellie/releases/tag/2.3.1).
