### ISSUE TITLE
Did something break in version 0.2.0 Chrome

### ISSUE THREAD

**Issue by alfip2022** [squarecat/ellie#9]
Been a beta user since HN and a paying member. Just wanted to let you know I don't know if something changed recently but version 0.2.0 on Windows 10 20H2 and Chrome. Ellie is no longer shown even though I have the extension in developer mode and have reloaded it. It has all the permissions required.

**Comment by alfip2022** [comment]
Please ignore, you went live with the chrome store version, so my early release version stopped working.

**Comment by Jivings** [comment]
Ah thanks for letting me know, I'm not sure why the older version stopped working but yes upgrade to the real extension now :)
